# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  catppuccin-fcitx5 = {
    pname = "catppuccin-fcitx5";
    version = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fcitx5";
      rev = "ce244cfdf43a648d984719fdfd1d60aab09f5c97";
      fetchSubmodules = false;
      sha256 = "sha256-uFaCbyrEjv4oiKUzLVFzw+UY54/h7wh2cntqeyYwGps=";
    };
    date = "2022-10-05";
  };
  catppuccin-fish = {
    pname = "catppuccin-fish";
    version = "0ce27b518e8ead555dec34dd8be3df5bd75cff8e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fish";
      rev = "0ce27b518e8ead555dec34dd8be3df5bd75cff8e";
      fetchSubmodules = false;
      sha256 = "sha256-Dc/zdxfzAUM5NX8PxzfljRbYvO9f9syuLO8yBr+R3qg=";
    };
    date = "2023-11-02";
  };
  fcitx5-pinyin-moegirl = {
    pname = "fcitx5-pinyin-moegirl";
    version = "20231114";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20231114/moegirl.dict";
      sha256 = "sha256-x+XkATiNMNbcSiN87MkRRvKiNuzvpmkDrtGkwdnIsYM=";
    };
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20240210";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20240210.dict";
      sha256 = "sha256-vNHS5n3TqSwpUx2wG26w7rK6jSqrvLANeG2n0vA4iYk=";
    };
  };
  librime-charcode = {
    pname = "librime-charcode";
    version = "3709ca7a39a7c14f9e02fa00489a9850fd5a907b";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "librime-charcode";
      rev = "3709ca7a39a7c14f9e02fa00489a9850fd5a907b";
      fetchSubmodules = false;
      sha256 = "sha256-KfKkpph+2ChQpkkGKubmpg/18uPX9qUHTqJT1PSGorI=";
    };
    date = "2024-02-10";
  };
  librime-lua = {
    pname = "librime-lua";
    version = "0f69bfa2f2724c513987855cad71611f8759c703";
    src = fetchFromGitHub {
      owner = "hchunhui";
      repo = "librime-lua";
      rev = "0f69bfa2f2724c513987855cad71611f8759c703";
      fetchSubmodules = false;
      sha256 = "sha256-GDQRAQ/eyaBh+qEssAPqd2+6FuCdvQWC2Q6s4w8A2HA=";
    };
    date = "2024-02-27";
  };
  librime-octagram = {
    pname = "librime-octagram";
    version = "bd12863f45fbbd5c7db06d5ec8be8987b10253bf";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-octagram";
      rev = "bd12863f45fbbd5c7db06d5ec8be8987b10253bf";
      fetchSubmodules = false;
      sha256 = "sha256-77g72tee4ahNcu3hfW1Okqr9z8Y6WrPgUhw316O72Ng=";
    };
    date = "2024-02-05";
  };
  librime-proto = {
    pname = "librime-proto";
    version = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-proto";
      rev = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
      fetchSubmodules = false;
      sha256 = "sha256-HdypebfmzreSdEQBwbvRG6sJZPASP+e8Tew+GrMnpOQ=";
    };
    date = "2023-10-17";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "c2e02af730d64e7b73b1c1102e0a4bd2eef073f5";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "c2e02af730d64e7b73b1c1102e0a4bd2eef073f5";
      fetchSubmodules = false;
      sha256 = "sha256-TlxalXNEkDyh7Ir8W7zLSzOsrgaQMEB2OTEkhP+McKA=";
    };
    date = "2024-02-28";
  };
}
